banking_system/bankapp/urls.py
from django.urls import path

from . import views

app_name='bankapp'
urlpatterns = [

    path('', views.demo, name='demo'),
]

banking_system/banking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bankapp.urls')),
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

banking_system/credentials/urls.py
from . import views
from django.urls import path

app_name="credentials"
urlpatterns = [

    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('messages', views.messages, name='messages'),


]

banking_system/credentials/models.py
from django.db import models

# Create your models here.

banking_system/bankapp/forms.py
# import the standard Django Forms

banking_system/bankapp/views.py
from django.http import HttpResponse, request
from django.shortcuts import render

from django.template import loader




def demo(request):
    template = loader.get_template("index.html")
    return HttpResponse(template.render())

banking_system/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse

from django.shortcuts import render, redirect
from django.template import loader


# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return render(request, "form.html")


        else:
            messages.info(request, "invalid credentials")
            return redirect('login')

    return render(request, "login.html")


def register(request):
    if request.method == 'POST':
        username = request.POST['username']

        password = request.POST['password']
        cpassword = request.POST['password1']

        if password == cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request, "username taken")
                return redirect('register')


            else:
                user = User.objects.create_user(username=username, password=password )
                user.save();
                return redirect('login')
        else:
            messages.info(request, "password not matched")
            return redirect('register')
        return redirect('/')

    return render(request, "register.html")


def logout(request):
    auth.logout(request)
    return redirect('/')


def messages(request):

    return render(request,"msg.html")

banking_system/templates/form.html
<!DOCTYPE html>
<html>
<head>
  <style>

body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: white;
}

* {
  box-sizing: border-box;
}




/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}


  .button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
.table{
font-size=30px;
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>
var subjectObject = {
  "South-kerala": {
    "Trivandrum": ["Kazhakootam", "Chala", "Thambanoor", "Venjaramood"],
    "Kollam": ["Kottarakara", "Kundara", "Kottiyam", "Shasthamkotta"],
    "Kottayam": ["Ettumanoor", "Pala", "Chenganacherry", "Ponkunnam"]
  },
  "North-kerala": {
    "Ernakulam": ["Kakkanad", "Vytila", "Kochi"],
    "Kannur": ["Payyanur", "Thalacherry", "Mattannur"]
  }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");
  var chapterSel = document.getElementById("chapter");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns
    chapterSel.length = 1;
    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
    //empty Chapters dropdown
    chapterSel.length = 1;
    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {
      chapterSel.options[chapterSel.options.length] = new Option(z[i], z[i]);
    }
  }
}
</script>
</head>
<body>
<form >
<h1>Fill the Form</h1>
{% csrf_token %}

<table>
  <tr>
    <td><label for="name">Name:</label></td>
    <td><input type="text" name="name" id="name" placeholder="Name"></td>
  </tr>
  <tr>
    <td><label for="dob">DOB:</label></td>
    <td><input type="date" name="dob" id="dob" placeholder="DOB"></td>
  </tr>
  <tr>
    <td><label for="age">Age:</label></td>
    <td><input type="number" name="number" id="number" placeholder="Age"></td>
  </tr>
  <tr>
    <td><label for="gender">Gender:</label></td>
    <td>Male: <input type="radio" name="gender" value="male">
      Female: <input type="radio" name="gender" value="female">
      Transgender: <input type="radio" name="gender" value="Transgender"></td>
  </tr>
  <tr>
    <td><label for="phoneNumber">Phone Number:</label></td>
    <td><input type="number" name="phoneNumber" id="phoneNumber"></td>
  </tr>
  <tr>
    <td><label for="email">Email:</label></td>
    <td><input type="text" name="email" id="email" placeholder="your email"></td>
  </tr>
  <tr>
    <td><label for="password">Password:</label></td>
    <td><input type="password" name="password" id="password"></td>
  </tr>
  <tr>
    <td><label for="address">Address:</label></td>
    <td><textarea name="address" id="address" placeholder="Address"></textarea></td>
  </tr>
<td>
<form name="form1" id="form1" action="/action_page.php">
Region: <select name="subject" id="subject">
    <option value="" selected="selected">Select region</option>
  </select>
  <br><br>
District: <select name="topic" id="topic">
    <option value="" selected="selected">Please select region first</option>
  </select>
  <br><br>
Branch: <select name="chapter" id="chapter">
    <option value="" selected="selected">Please select district first</option>
  </select>
  <br><br>
    </tr>
    </form>
   <tr>
    <td><label for="Account">Account Type</label></td>
    <td>
      <select id="account" name="account">
        <option value="">Choose</option>
        <option value="Savings">Savings</option>
        <option value="Current">Current</option>
      </select></td>
  </tr>

    <td><label for="material">Materials Required :</label></td>
    <td>
      <input type="checkbox" id="debit" name="materials[]" value="Debit Card">
      <label for="debit">Debit Card</label>
      <input type="checkbox" id="credit" name="materials[]" value="Credit Card">
      <label for="credit">Credit Card</label>
      <input type="checkbox" id="cheque" name="materials[]" value="Chequebook">
      <label for="debit">Cheque Book</label></td>


<tr>
<td>
    <li><a href="messages" class="button">Submit</a></li> <br>
</td>
  </tr>
  <tr>
  <td>
    <li><a href="logout" class="button">Logout</a></li>
  </td>
</tr>
</table>
</form>
</body>
</html>

banking_system/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Welcome to Dhana Bank</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Travello template project">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap4/bootstrap.min.css' %}">
<link href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/owl.theme.default.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'plugins/OwlCarousel2-2.2.1/animate.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/about_responsive.css'%}">
</head>
<body>

<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
							<div class="logo"><a href="{{index.html}}">Dhana Bank</a></div>
							<nav class="main_nav">
								<ul class="d-flex flex-row align-items-start justify-content-start">
									 <li><a href="{{index.html}}">Home</a></li>

									<li class="dropdown">
										<a href="#lala" class="dropdown-toggle" data-toggle="dropdown" >
										   Branches
										</a>
										<ul class="dropdown-menu" role="listbox" style="background-color:black;" >
										   <li><a href="https://en.wikipedia.org/wiki/Thiruvananthapuram" role="option">Trivandrum</a></li>
										   <li><a href="https://en.wikipedia.org/wiki/Kollam" role="option">Kollam</a></li>
										   <li><a href="https://en.wikipedia.org/wiki/Kottayam" role="option">Kottayam</a></li>
										   <li class="divider"></li>
										   <li><a href="https://en.wikipedia.org/wiki/Ernakulam" role="option">Ernakulam</a></li>
										   <li class="divider"></li>
										   <li><a href="https://en.wikipedia.org/wiki/Kannur" role="option">Kannur</a></li>
										</ul>
									 </li>





									{% if user.is_authenticated %}
									<li> Hello {{user.username}} </li>
									<li><a href="credentials/logout">Logout</a></li>
									{% else %}

									<li><a href="credentials/register">Register</a></li>

									<li><a href="credentials/login" class="btn btn-primary">Login</a></li>

									{% endif %}


								</ul>
							</nav>
							<div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>

							<!-- Hamburger -->

							<div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header_social d-flex flex-row align-items-center justify-content-start">
			<ul class="d-flex flex-row align-items-start justify-content-start">
				<li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-behance" aria-hidden="true"></i></a></li>
				<li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</header>


	<!-- Menu -->


	<!-- Home -->

	<div class="home">
		<div class="background_image" style="background-image:url({% static 'images/about3.jpg' %})"></div>
	</div>

	<!-- Search -->

	<!-- Footer -->

	<footer class="footer">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/footer_2.jpg'%}" data-speed="0.8"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="newsletter">
						<div class="newsletter_title_container text-center">
							<div class="newsletter_title">Subscribe to our newsletter to get the latest trends & news</div>
							<div class="newsletter_subtitle">Join our database NOW!</div>
						</div>
						<div class="newsletter_form_container">
							<form action="#" class="newsletter_form d-flex flex-md-row flex-column align-items-start justify-content-between" id="newsletter_form">
								<div class="d-flex flex-md-row flex-column align-items-start justify-content-between">
									<div><input type="text" class="newsletter_input newsletter_input_name" id="newsletter_input_name" placeholder="Name" required="required"><div class="input_border"></div></div>
									<div><input type="email" class="newsletter_input newsletter_input_email" id="newsletter_input_email" placeholder="Your e-mail" required="required"><div class="input_border"></div></div>
								</div>
								<div><button class="newsletter_button">subscribe</button></div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="row footer_contact_row">
				<div class="col-xl-10 offset-xl-1">
					<div class="row">

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">

								<div class="footer_contact_title">give us a call</div>
								<div class="footer_contact_list">
									<ul>
										<li>Office Landline: +44 5567 32 664 567</li>
										<li>Mobile: +44 5567 89 3322 332</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">

								<div class="footer_contact_title">Know more about our schemes</div>
								<div class="footer_contact_list">
									<ul style="max-width:190px">
										<li>www.dhanabank.com</li>
									</ul>
								</div>
							</div>
						</div>

						<!-- Footer Contact Item -->
						<div class="col-xl-4 footer_contact_col">
							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">

								<div class="footer_contact_title">send us a message</div>
								<div class="footer_contact_list">
									<ul>
										<li>dhanabank@gmail.com</li>
										<li>Office@dhanabank.com</li>
									</ul>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<div class="col text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Dhana Bank <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --> </div>

	</footer>
</div>

<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
<script src="{% static  'styles/bootstrap4/popper.js'%}"></script>
<script src="{% static 'styles/bootstrap4/bootstrap.min.js'%}"></script>
<script src="{% static 'plugins/greensock/TweenMax.min.js'%}"></script>
<script src="{% static 'plugins/greensock/TimelineMax.min.js'%}"></script>
<script src="{% static 'plugins/scrollmagic/ScrollMagic.min.js'%}"></script>
<script src="{% static 'plugins/greensock/animation.gsap.min.js'%}"></script>
<script src="{% static 'plugins/greensock/ScrollToPlugin.min.js'%}"></script>
<script src="{% static 'plugins/OwlCarousel2-2.2.1/owl.carousel.js'%}"></script>
<script src="{% static  'plugins/easing/easing.js'%}"></script>
<script src="{% static 'plugins/parallax-js-master/parallax.min.js'%}"></script>
<script src="{% static 'js/about.js'%}"></script>
</body>
</html>

banking_system/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
</head>
<body>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 20%;
  padding: 15px;
   margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
    margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: white;
  text-align: center;
  width:20%;
}
</style>
</head>
</body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="enter the username"><br>
    <input type="password" name="password" placeholder="enter the password"><br>
    <input type="submit" class="registerbtn" value="Login"><br>
</form>
    If you don't have an account sign up here

   <div class="container signin">
       <form action="register" ,method="post" >
    {% csrf_token %}
    <p>Dont have an account? <a href="register">Sign Up</a></p>

</form>
        </div>



</html>

banking_system/templates/msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application status</title>
</head>
<style>
     .button {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 12px 20px;
  margin: 5px 0 22px 0;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
}
h1{
    font-family: Arial;
    font-size: 40px;
    font-style: normal;
    font-weight: bold;
    color: brown;
    text-align: center;
    text-decoration: underline;
}
</style>
<body>
<h1>Your Application is Accepted!!!</h1><br>
<a href="{% url 'bankapp:demo' %}" class="button">Home</a>
</body>
</html>

banking_system/templates/register.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>
    <style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: black;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 20%;
  padding: 15px;
   margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
    margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
  opacity: 0.9;
}

.registerbtn:hover {
  opacity: 1;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: white;
  text-align: center;
  width:20%;
}
</style>
</head>
<body>
<h2>Register</h2>
<form action="register" method="post">
  {% csrf_token %}

  <input type="text" name="username" placeholder="enter the username"><br>
  <input type="password" name="password" placeholder="enter the password"><br>
  <input type="password" name="password1" placeholder="confirm password"><br>
  <input type="submit"  class="registerbtn" value="Register">

</form>
{% for msg in messages %}
{{msg}}
{%endfor %}

</body>
</html>